- type: gameMapPool
  id: SunriseMapPool
  maps:
  - SunriseDelta
  - SunriseBox
  - SunriseFland
  - SunriseMarathon
  - SunriseBagel
  - SunriseMeta
  - SunrisePlasma
  - DarvinReach
  - SunrisePacked
  - SunriseOasis
  - SunriseConvex
